
version: '3.8'

services:

  db:
    image: postgres:16.1
    container_name: tech-test
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
    ports:
      - "5432:5432"